name: Generate Snake Animation

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SVGs
        uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          svg_out_path: ./github-contribution-grid-snake.svg
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg
